site_name: 'USP Core Authenticate documentation'
docs_dir: './docs'                        # Where to find the English markdown files
site_dir: './generated'                      # Where to put the English HTML files
#site_url: 'https://github.com/waf'

theme:
  name: material
  custom_dir: './overrides/'                  # This is where the customization of the theme lives
  logo: assets/images/USP-Logo-2023-ohne-claim-lang-white1.webp                 # The logo is shared by all languages
  favicon: assets/images/favicon.png              # The favicon is shared by all languages
  language: en                                    # The build's language
extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search:
      lang: en                                      # Set language for search
  - swagger-ui-tag:
      supportedSubmitMethods: []
      validatorUrl: none

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Welcome: 'index.md'
  - Release Notes:
#      - Core Authenticate: 'changelog.md'
      - Secure Login Service: 'releasenotes.md'
  - Configuration:
    - Container Internals: 'container.md'
    - Settings:
      - General:
        - Authentication: 'authentication.md'
        - Challenge/Response: 'challenge_response.md'
        - Models: 'models.md'
        - Logging: 'logging.md'
      - OIDC OP:
        - OIDC Settings: 'oidc-settings.md'
        - Models: 'oidc-models.md'
      - SAML 2.0 IdP:
        - IdP Settings: 'saml-idp-settings.md'
        - Models: 'saml-idp-models.md'
    - Kubernetes Manifests:
      - Service: 'config_k8s_service.md'
      - Deployment: 'config_k8s_deployment.md'
      - Service: 'config_k8s_service.md'
      - Overrides: 'config_k8s_overrides.md'
      - Custom Files: 'config_k8s_files.md'
      - Secrets: 'config_k8s_secret.md'
  - Operation:
    - Core Authenticate Upgrade: 'upgrade.md'
  - SLS Documentation:
    - HTML: 'html-documentation.md'
    - PDF: 'pdf-documentation.md'
  - Downloads: 'downloads.md'
